WIP: Linalg lowering for aten.conv2d and aten.AdaptiveAvgPool2d
llvm/mlir-npcomp pull request #246
Opened 2021-07-08 22:49 UTC by cathyzhyi

1. Add m_TorchConstantIntList
2. Lowering for aten.conv2d
3. Lowering aten.AdaptiveAvgPool2d

2021-07-08 22:51 UTC, cathyzhyi commented
this change is blocked by upstream issues so can't be merged yet

2021-07-08 23:17 UTC, silvasean requested changes

2021-07-08 23:17 UTC, silvasean commented on lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
> +static bool constantIntListAsExpected(Value &value,
can you give this a name that matches the coding standard? https://llvm.org/docs/CodingStandards.html#name-types-functions-variables-and-enumerators-properly

I would call it `isConstantIntListMatching(Value &v, ArrayRef<int64_t> expected)`

2021-07-08 23:17 UTC, silvasean commented on lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
> +    rewriter.replaceOp(op, conv2d);
do you need a tensor.cast op here?

2021-07-09 13:59 UTC, cathyzhyi commented on lib/Conversion/TorchToLinalg/TorchToLinalg.cpp
> +    rewriter.replaceOp(op, conv2d);
Right. Thanks for catching this!

2021-07-09 19:19 UTC, silvasean commented
Is this still WIP? It still says WIP in the title an there are some remaining changes requested.

2021-07-09 19:25 UTC, cathyzhyi commented
> Is this still WIP? It still says WIP in the title an there are some remaining changes requested.

I removed the WIP and didn't find a proper way to block merging.
I can see 2 comments on my side and they are all addressed.

2021-07-09 19:26 UTC, silvasean approved these changes

2021-07-09 22:04 UTC, merged