Torch.sum lowering to Linalg
llvm/mlir-npcomp pull request #298
Opened 2021-09-03 19:41 UTC by ramiro050

Adds a lowering for the two versions of `torch.sum` (with and without dimensions specified). The lowering is based on the one used for `Tosa->Linalg` in `MLIR`.

In addition, this PR also includes a general `ConversionPattern` (`ConvertReduceOp`) that can be easily extended to include any other `torch` operations that result in a reduction of tensors.

## Issues

### Problem with `ResNet` test

The only problem I am having at the moment is that when I run the tests I wrote at the same time as the test for `ResNet18Module_basic` in https://github.com/llvm/mlir-npcomp/blob/main/frontends/pytorch/e2e_testing/torchscript/elementwise.py, at least one of the `sum` tests fails non-deterministically. If I run the test suite without the `ResNet18Module_basic`, my tests pass every single time.

### Broken invariant

In order to implement the version of `torch.sum` that reduces along every dimension, I had to refine the type in https://github.com/llvm/mlir-npcomp/blob/main/lib/Dialect/Torch/Transforms/RefineTypes.cpp by saying that `knowledge.hasSizes = true` while keeping the `knowledge.sizes` vector empty. This is needed because the result is supposed to be a zero ranked tensor. The problem is that this breaks the assert statement in the `ValueKnowledge` constructor:

```c++
assert(sizes.size() == 0 || hasSizes);
```

This does not prevent my code from running correctly, but I think this assert statement should be revisited, since zero-rank tensors are possible in `torch`.

2021-09-03 21:02 UTC, silvasean requested changes
Great work! Thanks for this patch. I just have a few minor stylistic nits

2021-09-03 21:04 UTC, silvasean commented
Also, btw, in npcomp we typically squash everything into a single commit and `push -f` when updating PR's.

2021-09-03 21:08 UTC, ramiro050 commented on lib/Dialect/Torch/Transforms/RefineTypes.cpp
> +  // FIXME: this breaks the assertion of the `ValueKnowledge` constructor
Oh, never mind. I completely misread the `assert` statement. I'll remove the `FIXME`

2021-09-03 21:15 UTC, silvasean commented
I tried reproducing the ResNet-induced nondeterminism, but I seem get get caught on the assertion:

```
python: ../external/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:257: const T &llvm::ArrayRef<mlir::Value>::operator[](size_t) const [T = mlir::Value]: Assertion `Index < Length && "Invalid index!"' failed.
```

Can you look into that? It seems like the CI is complaining about it too. It could be the source of the issue.

2021-09-03 21:19 UTC, silvasean commented on lib/Dialect/Torch/Transforms/RefineTypes.cpp
> +  // FIXME: this breaks the assertion of the `ValueKnowledge` constructor
I usually build with CMake using `-DLLVM_ENABLE_ASSERTIONS=ON` fwiw (even for `Release` or `RelWithDebInfo` builds) to help catch these things -- if it doesn't fire, I just don't even think about it :)

2021-09-03 22:23 UTC, silvasean commented
Can you clean up the commit message a little bit so our history is tidy?

2021-09-03 22:25 UTC, silvasean requested changes

2021-09-03 22:25 UTC, silvasean commented on lib/Dialect/Torch/Transforms/RefineTypes.cpp
> +      return visitReductionAlongDimIntListOp(meanDim, meanDim.dim(),
nit: can you format this? I recommend clang-format.

2021-09-03 22:30 UTC, ramiro050 commented
I think it's failing to build now because I accidentally added to the commit the changes that were just merged for the `llvm` project...

2021-09-03 23:12 UTC, ramiro050 commented
I've resolved the build issue. My branch should now be able to pass the `check-npcomp` and `check-frontends-pytorch` without a problem. The only thing remaining is the non-deterministic behavior with `tools/torchscript_e2e_test.sh`

2021-09-03 23:54 UTC, silvasean commented
I just tested locally and I am not seeing the nondeterministic error. I ran with `tools/torchscript_e2e_test.sh -f 'ReduceSumModule_basic|Res'` like 20 times with no errors.

2021-09-04 00:37 UTC, merged

2021-09-04 00:37 UTC, silvasean commented
Just merged it. Thanks a bunch!!

2021-09-04 00:38 UTC, ramiro050 commented
Interesting. Yeah, I just ran it a few times again on my machine and it also passes. It must have just been the `Assertion `Index < Length && "Invalid index!"' failed.` then. 

Awesome! Glad I could help!